apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: circle-detector

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - mosquitto.yaml
  - bridge.yaml
  - detector-daemonset.yaml
